// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3JS-bxR3-QUTsi00NRnkbFXqGMiee_A',
    appId: '1:350395580885:web:8a445172811c6e18a43d5c',
    messagingSenderId: '350395580885',
    projectId: 'proyectosmp-cb275',
    authDomain: 'proyectosmp-cb275.firebaseapp.com',
    storageBucket: 'proyectosmp-cb275.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdwiT3LlZXST3kt2-ylxfbamlDuKjS9vs',
    appId: '1:350395580885:android:96082758fe030d8da43d5c',
    messagingSenderId: '350395580885',
    projectId: 'proyectosmp-cb275',
    storageBucket: 'proyectosmp-cb275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYavQkhxCKXPYnZ6e_D8cl192VlnlHRrg',
    appId: '1:350395580885:ios:2bff63c115de1f76a43d5c',
    messagingSenderId: '350395580885',
    projectId: 'proyectosmp-cb275',
    storageBucket: 'proyectosmp-cb275.firebasestorage.app',
    iosBundleId: 'com.example.proyectoSmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYavQkhxCKXPYnZ6e_D8cl192VlnlHRrg',
    appId: '1:350395580885:ios:2bff63c115de1f76a43d5c',
    messagingSenderId: '350395580885',
    projectId: 'proyectosmp-cb275',
    storageBucket: 'proyectosmp-cb275.firebasestorage.app',
    iosBundleId: 'com.example.proyectoSmp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx3JS-bxR3-QUTsi00NRnkbFXqGMiee_A',
    appId: '1:350395580885:web:965d11f222c63523a43d5c',
    messagingSenderId: '350395580885',
    projectId: 'proyectosmp-cb275',
    authDomain: 'proyectosmp-cb275.firebaseapp.com',
    storageBucket: 'proyectosmp-cb275.firebasestorage.app',
  );
}
